### PR TITLE
Update ES-strings.po

### PR DESCRIPTION
**Pull request by Caballlero**

### CODE REVIEW

**Comment by roliverosc** [comment]
Hi @Caballero this strings are for Spanish from Span. Please, I would beg you not to contribute. What you can do is provide suggestions.

**Comment by Caballlero** [comment]
Do a suggest to specific locale , It is ridiculous, being same idiom. Feel free to fix.

**Comment by roliverosc** [comment]
You can think that it is something ridiculous but Kodi allows to use a language according to location, take advantage of that. Although you speak Spanish in Spain some Latin expressions are somewhat ridiculous. I already have some experience as a translator and I had to correct some addons from beginning to end because the expressions were ridiculous and meaningless for the Spanish language of Spain.

**Comment by Caballlero** [comment]
The conflict is speak spanish at low level,on any country speaking spanish, as example: the word coche to say car. that is a low level spanish. on my side I do not have problem to understand  spanish from spain I just did a translate which was missing. please work together

**Comment by roliverosc** [comment]
Agree without problem, two are better than one.

**Comment by roliverosc** [comment]
I think it's not convenient to merge. I am using certain guidelines to list the menus and addon options. I do not think it's convenient to change them. I think it will look better visually if we continue with those guidelines.

The string "30101" (Add to addon favs) I can not find the context in which it appears. I need to know when and how it appears.

**Comment by Caballlero** [comment]
I will close this,  but please @roliverosc be a better translater on your  certain guidelines.

**Pull request closed without merging**
